In [2]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd

In [3]:
# Create a 3x4 numpy array of all zeros
demo_matrix = np.array(([13,35,74,48], [23,37,37,38], [73,39,93,39]))

In [4]:
demo_matrix[0:3, 1:3]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [5]:
demo_array = np.arange(10)
print(demo_array)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
demo_array[0:7] = 5
print(demo_array)

[5 5 5 5 5 5 5 7 8 9]


In [7]:
demo_array = np.arange(0,10)
demo_array<3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [10]:
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus' ])
flowers['daisy']

5

In [9]:
print(flowers)

lily     2
rose     3
daisy    5
lotus    4
dtype: int64


In [11]:
# Create the DataFrame
data_customer = pd.DataFrame({
    'customer': [101, 102, 103, 104],
    'category': ['cat2', 'cat2', 'cat1', 'cat3'],
    'important': ['yes', 'no', 'yes', 'yes'],
    'sales': [123, 52, 214, 663]
})

# Find the number of customers in each category
category_counts = data_customer.groupby('category').size()

print(category_counts)

category
cat1    1
cat2    2
cat3    1
dtype: int64


In [12]:
print(data_customer)

   customer category important  sales
0       101     cat2       yes    123
1       102     cat2        no     52
2       103     cat1       yes    214
3       104     cat3       yes    663


In [13]:
data_customer['category'].unique()

array(['cat2', 'cat1', 'cat3'], dtype=object)

In [17]:
data_customer['category'].value_counts()

category
cat2    2
cat1    1
cat3    1
Name: count, dtype: int64

In [18]:
data_customer.sort(by='sales',ascending=False)

AttributeError: 'DataFrame' object has no attribute 'sort'

In [19]:
data_customer.sort_values(by='sales',ascending=False)

customer category important  sales
3       104     cat3       yes    663
2       103     cat1       yes    214
0       101     cat2       yes    123
1       102     cat2        no     52

In [20]:
data_customer.sort_values(by='sales',ascending=True)

customer category important  sales
1       102     cat2        no     52
0       101     cat2       yes    123
2       103     cat1       yes    214
3       104     cat3       yes    663

In [25]:

data_customer.loc[[1,2], ['customer', 'sales']]

customer  sales
1       102     52
2       103    214

In [26]:
# Create the DataFrame
data_cust = pd.DataFrame({
    'customer': [101, 102, 103, 104, 101, 103],
    'category': ['cat2', 'cat2', 'cat1', 'cat3', 'cat2', 'cat1'],
    'important': ['yes', 'no', 'yes', 'yes', 'yes', 'yes'],
    'sales': [123, 52, 214, 663, 204, 453]
})


In [27]:
data_cust.groupby(['customer'])['sales'].mean()

customer
101    163.5
102     52.0
103    333.5
104    663.0
Name: sales, dtype: float64

In [28]:
data_cust.groupby(['sales'])['customer'].mean()

sales
52     102.0
123    101.0
204    101.0
214    103.0
453    103.0
663    104.0
Name: customer, dtype: float64

In [31]:


data_cust.groupby(['customer'])['sales'].mean()

customer
101    163.5
102     52.0
103    333.5
104    663.0
Name: sales, dtype: float64